default: &default
  adapter: mysql2
  pool: 5
  encoding: utf8

development:
  <<: *default
  database: citemethis_dev
  host: localhost

staging:
  <<: *default
  database: citemethis_staging

production:
  <<: *default
  database: citemethis_production
  host: prod-db.ckmzy5mny0df.eu-west-1.rds.amazonaws.com:3306
  username: admin
  password: klmojoman
